name: apps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.1.3
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  fl_chart: ^0.69.0
  table_calendar: ^3.0.9
  pinput: ^5.0.0
  flutter_bloc: ^8.1.3
  http: ^1.2.2
  flutter_launcher_icons: ^0.14.1
  shared_preferences: ^2.3.2
  email_otp: ^3.0.2
  google_sign_in: ^6.2.2
  pdf: ^3.6.0
  printing: ^5.5.0
  path_provider: ^2.1.5
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  fonts:
    - family: OdorMeanChey
      fonts:
        - asset: assets/fonts/OdorMeanChey-Regular.ttf
    - family: NotoSanCondensed
      fonts:
        - asset: assets/fonts/NotoSans_Condensed-Black.ttf
    - family: NotoSanSemiBold
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
    - family: Manjari
      fonts:
        - asset: assets/fonts/Manjari-Bold.ttf


flutter_icons:
  remove_alpha_ios: true
  android: true
  ios: true
  image_path: "assets/images/Logos Apps.png"